/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketRouteImport } from './routes/market'
import { Route as DiagnoseRouteImport } from './routes/diagnose'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDiagnoseRouteImport } from './routes/api/diagnose'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnoseRoute = DiagnoseRouteImport.update({
  id: '/diagnose',
  path: '/diagnose',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiagnoseRoute = ApiDiagnoseRouteImport.update({
  id: '/api/diagnose',
  path: '/api/diagnose',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnose': typeof DiagnoseRoute
  '/market': typeof MarketRoute
  '/api/chat': typeof ApiChatRoute
  '/api/diagnose': typeof ApiDiagnoseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnose': typeof DiagnoseRoute
  '/market': typeof MarketRoute
  '/api/chat': typeof ApiChatRoute
  '/api/diagnose': typeof ApiDiagnoseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnose': typeof DiagnoseRoute
  '/market': typeof MarketRoute
  '/api/chat': typeof ApiChatRoute
  '/api/diagnose': typeof ApiDiagnoseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diagnose' | '/market' | '/api/chat' | '/api/diagnose'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diagnose' | '/market' | '/api/chat' | '/api/diagnose'
  id: '__root__' | '/' | '/diagnose' | '/market' | '/api/chat' | '/api/diagnose'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnoseRoute: typeof DiagnoseRoute
  MarketRoute: typeof MarketRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDiagnoseRoute: typeof ApiDiagnoseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnose': {
      id: '/diagnose'
      path: '/diagnose'
      fullPath: '/diagnose'
      preLoaderRoute: typeof DiagnoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diagnose': {
      id: '/api/diagnose'
      path: '/api/diagnose'
      fullPath: '/api/diagnose'
      preLoaderRoute: typeof ApiDiagnoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnoseRoute: DiagnoseRoute,
  MarketRoute: MarketRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDiagnoseRoute: ApiDiagnoseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
